version: '3.7'

services:
  spring_boot_app:
    container_name: back
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - postgres
      - springnet
  react_app:
    container_name: front
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000" # Host machine : Container
    networks:
      - springnet
    stdin_open: true
  db:
    container_name: gr_db
    image: postgres
    environment:
      POSTGRES_DB: courses_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
  pgadmin:
    container_name: db_explorer
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  springnet:
  postgres:

volumes:
  postgres:
  pgadmin: